language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_install:
- cd generate; npm install; cd ..
script:
- lsc generate/bin/generate.ls
cache:
  directories:
  - generate/node_modules
  - node_modules
deploy:
  provider: s3
  bucket: radiobadger.com
  skip_cleanup: true
  local-dir: out
  region: eu-west-1
  access_key_id:
    secure: Wu/45RFK/z8tC0zSgkC1YrnPYVaZcSd37EoznkDM09x8tGTp1Jbq3pG/iA7eeeDtCxxV6API6B5KLvc76KHym59aE7U6qyzcAj0ZInxWjfvfl+TkDKtsl0RR+t7Q2+BpilmGPK4pkmirGftCqKxOVTYOPmt21ZrVY0ONbKtTr88=
  secret_access_key:
    secure: C/+IdAJLu9LSqgfQ3x9jHWNK22YKvmx4674dYD1h15CX3o5VqfzRojlnJb25QEAC9BB0vI0sGADgB1uqBELa5atfCHg08RS0qKrI9wnghOmH8RGVW6BGSIRs1hS6x5II1AzbqcLd5B+rYWme5vO0bHf+O3gONfpw4l7sP/kx7Rs=
