language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
before_install:
- cd generate; npm install; cd ..
env:
  global:
  - S3_BUCKET=radiobadger.com
script:
- lsc generate/bin/generate.ls
cache:
  directories:
  - generate/node_modules
  - node_modules
deploy:
  provider: s3
  bucket: radiobadger.com
  skip_cleanup: true
  local-dir: out
  endpoint: radiobadger.com.s3-website-eu-west-1.amazonaws.com
  region: eu-west-1
  access_key_id:
    secure: "HFoeDF64RamK86QORLBjoya8Qdw69cU4Q7Rv2I7cZR32Zo4YJXau2pvtAo9rzHpmzUQga9/DbjsPdcPqm9A3OOooHNjj9wjiGZv3DcFu5vDfiq+qmdy1E8/eoDDTnMZA/eGc9wCEN3Ct6I3neJC+3a1LcGQiz01SfVqybEDzpNs="
  secret_access_key:
    secure: "EaNuxMTxmiLngF4bLcdnrdoZtbZ5fQJnXIh1CNV/NYM/5ZtMPDQMF3O9/mnstMhRfph9pEkvFf/tD1MdKVQvyk3w8tCyV8v7QRdQ+HK0q+CdiN0zSdwZ63IyB9n5mDkalzeOEozxxcvNvTy0+E/IobGSdqo4UPxejW7mDbqCXfc="
